/// DO NOT EDIT THIS FILE. IT IS GENERATED !!!

#pragma once

#include <stdint.h>
#include <string>

#include "psi/shared/ipc/IPCCallback.h"

namespace psi::logger {

class ILogger
{
public:
    virtual ~ILogger() = default;

    using OnClientRegistered = psi::ipc::IPCCallback<uint16_t>;

    virtual void registerClient(std::string, OnClientRegistered) = 0;
    virtual void log(uint16_t, std::string) = 0;
};

} // namespace psi::logger
